{
 "title": "REST Quickstat",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rest_request_sum{application=\"$application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rest_response_size_total{application=\"$application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reqs/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rest_request_sum{application=\"$application\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 2XX/sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rest_request_sum{application=\"$application\", status=~\"2.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 4XX/sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rest_request_sum{application=\"$application\", status=~\"4.*\"}[$__interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 5XX/min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rest_request_sum{application=\"$application\", status=~\"5.*\"}[$__interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reqs/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(rest_request_sum{application=~\"$application\"}[$__rate_interval])) by (method,path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Reqs/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(rest_request_sum{application=~\"$application\"}[$__rate_interval])) by (method,path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Top 10 Request by Status/sec",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status, method, path) (rate(rest_request_sum{application=~\"$application\"}[$__rate_interval]))",
     "legendFormat": "{{status}} - {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(rest_request_duration_bucket{application=~\"$application\"}[$__rate_interval])) by (method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  }
 ]
}