scrape_configs:
  - job_name: 'QuickStatMetrics'
    metrics_path: '/'
    scrape_interval: 3s
    static_configs:
      - targets: ['172.23.0.1:3242']
        labels:
          application: 'Quickstat'
  - job_name: 'pushgateway'
    metrics_path: /metrics
    scheme: http
    honor_labels: true
    static_configs:
      - targets: ['localhost:9091']
        labels:
          application: 'Quickstat'